dnsSettings:
  dnsServerDomain: "dnsserver.com"
  dnsServerLocalEndPoints:
    - "0.0.0.0:53"
  defaultRecordTtl: 3600
  dnssecValidation: true
  enableDnsOverHttps: true
  enableDnsOverTls: true
  enableDnsOverQuic: true

zones:
  - zone: "example2.com"
    type: "Primary"
    useSoaSerialDateScheme: true
    primaryNameServerAddresses:
      - "ns1.example2.com"
      - "ns2.example.com"
    aclSettings:
      queryAccess: "Allow"
      zoneTransfer: "AllowOnlyZoneNameServers"
      notify: "ZoneNameServers"
      update: "AllowOnlyZoneNameServers"

  - zone: "sub.example.com"
    type: "Secondary"
    primaryNameServerAddresses:
      - "ns1.example.com"
    zoneTransferProtocol: "Tls"
    tsigKeyName: "example.com-key"
    validateZone: true

records:
  - domain: "www.example2.com"
    type: "A"
    ttl: 3600
    ipAddress: "192.168.1.1"
    ptr: true

  - domain: "mail.example2.com"
    type: "MX"
    ttl: 3600
    exchange: "mail.example2.com"
    preference: 10

  - domain: "example2.com"
    type: "TXT"
    ttl: 3600
    text: "v=spf1 ip4:192.168.1.1 -all"

apps:
  - name: "Advanced Blocking"
    url: "https://download.technitium.com/dns/apps/AdvancedBlockingApp-v8.zip"
    config:
      enableBlocking: true
      blockListUrlUpdateIntervalHours: 24
      networkGroupMap:
        "0.0.0.0/0":      "home"
        "::/0":           "home"
      groups:
        - name: home
          enableBlocking: true
          allowTxtBlockingReport: true
          blockAsNxDomain: false
          blockingAddresses: [ "0.0.0.0", "::" ]
          # allowed:
          #   - example.com
          #   - "*.my-smart-home.local"
          # blocked:
          #   - annoyingads.com
          blockListUrls:
            - "https://raw.githubusercontent.com/xRuffKez/NRD/refs/heads/main/lists/14-day/wildcard/nrd-14day_wildcard.txt"
            - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt"
            - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass-onlydomains.txt"
            - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-onlydomains.txt"
            - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nosafesearch-onlydomains.txt"
            - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns-onlydomains.txt"

  - name: "Advanced Forwarding"
    url: "https://download.technitium.com/dns/apps/AdvancedForwardingApp-v3.1.zip"
    config:
      appPreference: 200
      enableForwarding: true
      proxyServers:
        - name: "local-proxy"
          type: "socks5"
          proxyAddress: "localhost"
          proxyPort: 1080
          proxyUsername: null
          proxyPassword: null
      forwarders:
        - name: "quad9-doh"
          proxy: null
          dnssecValidation: true
          forwarderProtocol: "Https"
          forwarderAddresses:
            - "https://dns.quad9.net/dns-query (9.9.9.9)"
        - name: "cloudflare-google"
          proxy: null
          dnssecValidation: true
          forwarderProtocol: "Tls"
          forwarderAddresses:
            - "1.1.1.1"
            - "8.8.8.8"
        - name: "quad9-tls-proxied"
          proxy: "local-proxy"
          dnssecValidation: true
          forwarderProtocol: "Tls"
          forwarderAddresses:
            - "9.9.9.9"
      networkGroupMap:
        "0.0.0.0/0": "everyone"
        "[::]/0": "everyone"
      groups:
        - name: "everyone"
          enableForwarding: true
          forwardings:
            - forwarders:
                - "quad9-doh"
              domains:
                - "example.com"
            - forwarders:
                - "cloudflare-google"
              domains:
                - "*"
          adguardUpstreams:
            - proxy: null
              dnssecValidation: true
              configFile: "adguard-upstreams.txt"