apiVersion: v1
kind: ConfigMap
metadata:
  name: technitium-config
data:
  config.yaml: |
    dnsSettings:
      dnsServerDomain: "example.com"
      defaultRecordTtl: 3600
      useSoaSerialDateScheme: true
      dnssecValidation: true
      dnsServerLocalEndPoints:
        - "0.0.0.0:53"
        - "[::]:53"

    zones:
      - zone: "example.com"
        type: "Primary"
        useSoaSerialDateScheme: true
        validateZone: true

    records:
      - domain: "example.com"
        type: "A"
        ipAddress: "192.168.1.1"
        ttl: 3600
      - domain: "www.example.com"
        type: "CNAME"
        cname: "example.com"
        ttl: 3600