apiVersion: v1
kind: ServiceAccount
metadata:
  name: technitium-configurator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: technitium-configurator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch"]
  resourceNames: ["technitium-token"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: technitium-configurator
subjects:
- kind: ServiceAccount
  name: technitium-configurator
roleRef:
  kind: Role
  name: technitium-configurator
  apiGroup: rbac.authorization.k8s.io