apiVersion: v1
kind: Secret
metadata:
  name: technitium-credentials
type: Opaque
stringData:
  username: admin
  password: your-secure-password
---
apiVersion: v1
kind: Secret
metadata:
  name: technitium-token
type: Opaque
stringData:
  token: ""  # This will be populated by the init container