apiVersion: v1
kind: ConfigMap
metadata:
  name: technitium-config
data:
  config.yaml: |
    dnsSettings:
      dnsServerDomain: "example.com"
      defaultRecordTtl: 3600
      useSoaSerialDateScheme: true
      dnssecValidation: true
      dnsServerLocalEndPoints:
        - "0.0.0.0:53"
        - "[::]:53"
    zones:
      - zone: "example.com"
        type: "Primary"
        useSoaSerialDateScheme: true
        validateZone: true
    records:
      - domain: "example.com"
        type: "A"
        ipAddress: "192.168.1.1"
        ttl: 3600
      - domain: "www.example.com"
        type: "CNAME"
        cname: "example.com"
        ttl: 3600
---
apiVersion: v1
kind: Secret
metadata:
  name: technitium-credentials
type: Opaque
stringData:
  username: admin
  password: your-secure-password
  new_password: your-new-secure-password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: technitium-configurator
spec:
  template:
    spec:
      serviceAccountName: technitium-configur
      initContainers:
      - name: change-password
        image: ashtonian/technitium-configurator:latest
        command:
          - change-password
        env:
          - name: DNS_API_URL
            valueFrom:
              configMapKeyRef:
                name: technitium-config
                key: dns_api_url
          - name: DNS_USERNAME
            valueFrom:
              secretKeyRef:
                name: technitium-credentials
                key: username
          - name: DNS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: technitium-credentials
                key: password
          - name: DNS_NEW_PASSWORD
            valueFrom:
              secretKeyRef:
                name: technitium-credentials
                key: new_password
      containers:
      - name: technitium-configurator
        image: ashtonian/technitium-configurator:latest
        command:
          - configure
          - /app/config.yaml
        env:
          - name: DNS_API_URL
            valueFrom:
              configMapKeyRef:
                name: technitium-config
                key: dns_api_url
          - name: DNS_USERNAME
            valueFrom:
              secretKeyRef:
                name: technitium-credentials
                key: username
          - name: DNS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: technitium-credentials
                key: new_password
        volumeMounts:
          - name: config-volume
            mountPath: /app/config.yaml
            subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: technitium-config
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: technitium-configur
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: technitium-configur
subjects:
- kind: ServiceAccount
  name: technitium-configur
  namespace: default
roleRef:
  kind: Role
  name: technitium-configur
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: technitium-configur